name: Update README with Joke

on:
  schedule:
    - cron: "0 12 * * *" # every day at noon UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate new joke
        run: |
          node jokes.js > joke.txt
      - name: Update README.md
        run: |
          sed -i '/<!-- JOKE START -->/,/<!-- JOKE END -->/c\<!-- JOKE START -->\n'"$(cat joke.txt)"'\n<!-- JOKE END -->' README.md
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update joke"
          git push
